server:
  port: 8762

---
spring:
  application:
    name: service-test

---
eureka:
  client:
    service-url:
      defaultZone: http://192.168.103.105:8768/eureka/
    healthcheck:
          enabled: true #开启健康检查
  instance:
    lease-renewal-interval-in-seconds: 10 #续约更新时间为30秒
    lease-expiration-duration-in-seconds: 30 #续约到期时间为90秒