server:
  port: 8765

---
spring:
  application:
    name: service-feign

---
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

---
#打开feign的断路器。 feign自带断路器
feign:
  hystrix:
    enabled: true