server:
  port: 8771
---
spring:
  application:
    name: service-turbine
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
---
turbine:
  app-config: service-test,client-miya
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true
  instance-url-suffix:
    default: actuator/hystrix.stream